server:
  port: 8004
  
spring:
  application:
    name: checkin-service  
  
  data:
    mongodb:
      host: localhost
      port: 27017
      database: CheckInDB
      
management:
  endpoints:
    web:
      exposure:
        include:
        - hystrix.stream

logging:
  level:
    '[com.user.service.CheckInServiceImpl]' : info       
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

  file:
    path: logs 
              