server:
  port: 8000
  
spring:
  application:
    name: user-service
    
  data:
    mongodb:
      host: localhost
      port: 27017
      database: UserDB
      
management:
  endpoints:
    web:
      exposure:
        include:
        - hystrix.stream

logging:
  level:
    '[com.user.service.UserServiceImpl]' : info       
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

  file:
    path: logs 
