server:
  port: 8085
eureka:
 instance:
   hostname: localhost
 client:
   service-url:
    defaultZone: http://localhost:8761/eureka/
spring:
 application:
  name: api-gateway


 cloud:
    gateway:
      routes:
      - id: user-service
        uri: http://localhost:8000/
        predicates:
        - Path=/user/**,/authenticate
        filters:
        - StripPrefix=1
      - id: flight-service
        uri: http://localhost:8001/
        predicates:
        - Path=/flight/**
        filters:
        - StripPrefix=1
      - id: booking-service
        uri: http://localhost:8002/
        predicates:
        - Path=/booking/**
        filters:
        - StripPrefix=1
      - id: fare-service
        uri: http://localhost:8003/
        predicates:
        - Path=/fare/**
        filters:
        - StripPrefix=1
      - id: checkin-service
        uri: http://localhost:8004/
        predicates:
        - Path=/checkin/**
        filters:
        - StripPrefix=1

#zuul:
#  routes:
#    user-service:
#      path:  /user/**
#      url: lb://user-service
#
#    flight-service:
#      path:  /flight/**
#      url: lb://flight-service
#
#    booking-service:
#      path: /booking/**
#      url: lb://booking-service
#
#    fare-service:
#      path: /fare/**
#      url: lb://fare-service
#
#    checkin-service:
#      path: /checkin/**
#      url: lb://checkin-service
#        